"""
Copyright 2026 Alex

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0
"""

import qanotz_core.utils.os as os
import random
import string

class File:
    def __init__(self, path: str):
        self.path = path

    def read(self) -> str:
        with open(self.path, "r") as f:
            return f.read()
    
    def write(self, content: str) -> None:
        with open(self.path, "w") as f:
            f.write(content)

    def append(self, content: str) -> None:
        with open(self.path, "a") as f:
            f.write(content)

class QAFile(File):
    def __init__(self, path: str) -> None:
        super().__init__(path)
        self.content: str
        self.last_modified: str = ""
        self.label: str = ""

def generate_random_filename(length: int = 16) -> str:
    characters = string.ascii_letters + string.digits
    random_filename = ''.join(random.choice(characters) for _ in range(length))
    return random_filename

if __name__ == "__main__":
    appdata_dir = os.get_appdata_dir()
    appdata_dir = f"{appdata_dir}/qanotz_cli"
    os.ensure_dir(appdata_dir)
    print(f"AppData Directory: {appdata_dir}")

    file_path = f"{appdata_dir}/autogen.txt"
    test_content: str = "THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY, ONLY DELETE THIS FILE TO REGENERATE IT.\n\nThis file is used for testing the File class in qanotz_cli.utils.filesystem. It should be automatically generated when you run this file, and it should contain this text."

    file = File(file_path)

    file.write(test_content)
    print(file.read())
    assert file.read() == test_content

    print(generate_random_filename())