"""
Copyright 2026 Alex

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0
"""

import qanotz_core.utils.os as os_utils
from qanotz_core.data.parser import parse
from qanotz_core.utils.filesystem import File, QAFile, generate_random_filename

class DataManagerInstance:
    def __init__(self, file_loc: str) -> None:
        appdata_dir = os_utils.get_appdata_dir()
        self.data_path = f"{appdata_dir}/qanotz"

        os_utils.ensure_dir(self.data_path)

        self.file = File(self.data_path + file_loc)

        try:
            self.file.read()
        except Exception:
            self.file.write('')

class LogManagerInstance(DataManagerInstance):
    def __init__(self) -> None:
        self.log_file = "/qalogs.log"
        super().__init__(self.log_file)

    def log_message(self, msg: str):
        self.file.append("\n" + msg)
        print(self.file.read())

class DatabaseManagerInstance(DataManagerInstance):
    def __init__(self):
        self.db_lookup = "/dblookup.dbl"
        super().__init__(self.db_lookup)

        os_utils.ensure_dir(self.data_path + '/qafiles')

        raw = self.file.read()
        self.lookup = parse(raw, lookup_mode=True)

        self.current_qa: QAFile

    def open_qa(self, file_name: str):
        self.current_qa = QAFile(self.data_path + "/qafiles/" + file_name)

    def search_qas(self, query: str):
        results: list[tuple[str, str]] = []

        for _, file_entry in self.lookup.items():
            metadata = file_entry.get("metadata", {})
            for _, meta in metadata.items():
                if meta.get("id") == "l" and query.lower() in meta.get("body", "").lower():
                    # return the file path (file body) and the label/body of the metadata
                    results.append((meta.get("body"), str(file_entry.get("body"))))

        return results

    def create_qafile(self, content: str):
        filename = f"{generate_random_filename()}.qan"

        qafile = QAFile(f"{self.data_path}/qafiles/{filename}")
        qafile.write(content)

        files = self.lookup.__len__()
        parsed_content = parse(content, include_types = "tq")
        file_append_content = f"\n\n{{f {files} {filename} \n"
        file_append_content += f"{{m l {parsed_content[0]['body']}}} \n"
        file_append_content += f"{{m m {os_utils.get_datetime()}}}}}"

        self.file.append(file_append_content)

        # reparse dblookup because we wrote to it
        raw = self.file.read()
        self.lookup = parse(raw, lookup_mode=True)

        self.current_qa = qafile

    def save_qafile(self, content: str):
        self.current_qa.write(content)

if __name__ == "__main__":
    db = DatabaseManagerInstance()
    log = LogManagerInstance()

    print(f"Database initialized at: {db.file.path}")
    print(f"Log file is located at: {log.file.path}")

    log.log_message("This message was autogenerated while testing the LogManagerInstance in QANotz.")

    print(db.search_qas("c"))

    # I am aware of how long this file is, but on the bright side, you get to learn about Rust!
    db.create_qafile("""
{t Learning Rust}

{q 1 Where does all this information come from, and what can I reference in the future?
    {a 1 The Rust Book (https://doc.rust-lang.org/book/)}
    {a 2 The 'rustup doc' command
        {d c This is the Rust Book, but offline in your terminal}
    }
}

{q 1 How do I start a Rust program / what are some key features?
    {a 1 Use a main() function!
        {d c A function is written like fn function_name()}
        {d c Encase the function body in brackets}
    }

    {a 2 Start writing with 'Hello, World'
        {d c Write a 'Hello, World' statement with println!("Hello, World");}
    }

    {a 3 Always remember to add semicolons after each line}
}

{q 2 What is Cargo and what does it do?
    {a 1 It is Rust's package manager
        {d c Used for project dependancies}
    }

    {a 2 Cargo doesn't only grab dependancies, it manages building code and the libraries it depends on.
        {d c Cargo does a lot!}
    }
}

{q 3 Variables: how do they work?
    {a 1 Variables are immutable by default
        {d c Write a variable like 'let x = 5;'}
        {d c Make it mutable with the 'mut' keyword (e.g. 'let mut y = 12;')}
    }
}

                     """)


