"""
Copyright 2026 Alex

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0
"""

from qanotz_core.data.data import DataManagerInstance

class Logger(DataManagerInstance):
    def __init__(self) -> None:
        self.log_file = "/qalogs.log"
        super().__init__(self.log_file)

    def log_message(self, msg: str):
        self.file.append("\n" + msg)
        print(self.file.read())

if __name__ == "__main__":
    log = Logger()
    print(f"Log file is located at: {log.file.path}")

    log.log_message("This message was autogenerated while testing the LogManagerInstance in QANotz.")